### ISSUE TITLE
ruleset updater

### ISSUE THREAD

**Issue by netflash** [wazuh/ossec-wazuh#13]
@snaow I just noticed that you copied updater to this repo - development branch.
What is your approach with it ? Are you going to completely get rid of ossec-rules repo and move everything here ?
I'm asking in terms of creating a proper Dockefile that will support ruleset updates.

**Comment by snaow** [comment]
Hi,

We are not getting rid of ossec-rules repo, we are going to include ruleset automatic updater on ossec-wazuh default installation.

Our goal is make things easy to users who desire to keep updated their OSSEC installation.

ossec-rules repository will be active and we will respect the current directory structure.

Thanks for your interest,

snaow.
