### ISSUE TITLE
UDP bad chksum when i try to add an agent

### ISSUE THREAD

**Issue by gionniboy** [wazuh/ossec-wazuh#21]
Hi,
i'm an ossec user by some time and i recentely knew your project: is amazing.
I have an ossec server but now i setup a new elk-ossec server with your ossec fork.
I added to new elk-ossec all my agents BEFORE the update to ossec-wazuh of agents.
All ok.
i upgrade the agetns: all ok.
Now i have a new vps: so i install ossec-wazuh without install/config before the ossec-hids and, when i try to connect the agent to the server, the UDP checksum go bad.
i open a tcpdump in the elk-ossec server
[root@elk bin]# tcpdump -i eth0 -vvv -X port 1514
and i see the packet arrived from my agent client
 vps.mydomain.com.54467 > 10.255.255.3.fujitsu-dtcns: [udp sum ok] UDP, length 73
 10.255.255.3.fujitsu-dtcns > vps.mydomain.com.54467: [bad udp cksum 83de!] UDP, length 73

so the connection go wrong. it repeat this try without work.
I investigate if i had network trouble but all it's ok for me.
So i try removing ossec-wazuh and installing ossec-hids and re-adding the client:
all ok now !!! no bad chksum on udp packet.
After that i upgrade to ossec-wazuh and all works fine.

Thanks you for all.

Gionni

**Comment by santiago-bassett** [comment]
Hi @gionniboy,

thanks for your nice words about the project. We are excited about it and working on new features that we plan to release soon.

We also have those UDP checksum errors, but that is most likely a tcpdump issue, more than a network one. See this explanation:

https://sokratisg.net/2012/04/01/udp-tcp-checksum-errors-from-tcpdump-nic-hardware-offloading/

Are you experiencing any weird behavior in OSSEC communications? Anything not working as expected? If everything is working fine I wouldn't worry about them.

I hope it helps,

Santiago.

**Comment by gionniboy** [comment]
no, all is going ok now. thanks for the hint about tcpdump, i didn't knew that.
see you soon.

Gionni
