### ISSUE TITLE
preloaded-vars.conf USER_INSTALL_TYPE variable different?

### ISSUE THREAD

**Issue by pjmorr** [wazuh/ossec-wazuh#22]
I modified my previous bootstrap code used with ossec-hids to try and use ossec-wazuh.  There seems to be some issue with the USER_INSTALL_TYPE variable.  Maybe a problem in my code?
<portions cut out for brevity>:
```
git clone https://github.com/wazuh/ossec-wazuh.git
  cat<<EOF > ossec-wazuh/etc/preloaded-vars.conf
  # preloaded-vars.conf, Daniel B. Cid (dcid @ ossec.net).
  #
  # Use this file to customize your installations.
  # It will make the install.sh script pre-load some
  # specific options to make it run automatically
  # or with less questions.

  # PLEASE NOTE:
  # When we use n or y in here, it should be changed
  # to n or y in the language your are doing the
  # installation. For example, in portuguese it would
  # be s or n.

  # USER_LANGUAGE defines to language to be used.
  # It can be \"en\", \"br\", \"tr\", \"it\", \"de\" or \"pl\".
  # In case of an invalid language, it will default
  # to English \"en\"
  USER_LANGUAGE=\"en\"     # For english
  #USER_LANGUAGE=\"br\"     # For portuguese


  # If USER_NO_STOP is set to anything, the confirmation
  # messages are not going to be asked.
  USER_NO_STOP=\"y\"


  # USER_INSTALL_TYPE defines the installation type to
  # be used during install. It can only be \"local\",
  # \"agent\" or \"server\".
  #USER_INSTALL_TYPE=\"local\"
  USER_INSTALL_TYPE=\"agent\"
  #USER_INSTALL_TYPE=\"server\"
  ...
```
seems to crash and not finish the install when it hits the USER_INSTALL_TYPE, either it does not like the \ or has the type changed?

**Comment by snaow** [comment]
Hi @pjmorr,

Thanks for using Wazuh.

I think you can't scape double quotes on `etc/preloaded-vars.conf` I ran some tests and It won't work using the slash character, please try not using it.

Using the slashes I got the error:
` Error 0x4.
 Wrong installation type. It can only be agent, server or local.
`
Are you getting the same error?

Like I said, try removing the slashes:

```
# USER_INSTALL_TYPE defines the installation type to
# be used during install. It can only be "local",
# "agent" or "server".
#USER_INSTALL_TYPE="local"
USER_INSTALL_TYPE="agent"
#USER_INSTALL_TYPE="server"
```



Thanks, please don't doubt to ask if you need any help,

Pedro S.

**Comment by pjmorr** [comment]
That is the error, weird that I don't get the issue in the other variables.  I will try it right now.

Thanks.

**Comment by snaow** [comment]
That is because OSSEC won't check the content of other variables until it gets there, the first check it does is the "USER_INSTALL_TYPE" .
Other variables are not working neither. OSSEC extracts from the variable the following:

Using escape character:
`USER_INSTALL_TYPE: "server"`

Not using escape character:
`USER_INSTALL_TYPE: server`

And "server" does not match with any installation type.

Hope it helps to understand the issue.

Best regards,
Pedro S.

**Comment by pjmorr** [comment]
Thank you works perfectly now in aws bootstrap.  awesome!

**Comment by snaow** [comment]
Glad to hear!

Do you have any additional question? Do you mind if I close the issue? 
If you require any further information, let us know, we are happy to help.

Best regards,
Pedro S.

**Comment by pjmorr** [comment]
Nope, sorry to bother. Thanks
