### ISSUE TITLE
Geo IP Mapping for Windows Logs

### ISSUE THREAD

**Issue by stephenh1991** [wazuh/ossec-wazuh#26]
Hi!

Using the Wuzah Ossec fork with ELK and I can't seem to get the GEOIP dashboards in Kibana to display remote addresses from Windows logs.

I can see the filter I need to use "Source Network Address" instead of "srcip" in the Logstash config template. However I don;t get any Geo IP results in the front end.

Any pointers?

Thanks,
Steve

**Comment by santiago-bassett** [comment]
Hi Stephen,

if I understood it correctly you modified "srcip" field in Logstash config file? did you also change it for the elasticsearch template? See the files below:

https://github.com/wazuh/ossec-wazuh/blob/master/extensions/logstash/01-ossec.conf#L10
https://github.com/wazuh/ossec-wazuh/blob/master/extensions/elasticsearch/elastic-ossec-template.json#L274

I hope this helps

**Comment by snaow** [comment]
Hi @stephenh1991,

I think you want to see the Windows event log field "Source Network Address" in our Kibana Dashboards, to do it first we need to extract the "srcip" with OSSEC decoders and rules, if OSSEC can extract the IP from the EventLog, it will be shown at Kibana.

Could you send us a log example where source network address field be present?
Thanks.

Best regards,

Pedro S.

**Comment by stephenh1991** [comment]
Hi Pedro,

Thanks for the reply on this, sorry if I'm asking a silly question (very
new to the ELK stack). So to have this information display in Kibana I
would also need to modify the Value in the Elasticsearch template? This is
because Kibana leverages ES to query Logstash?

Makes sense if that's correct!

The example logfile that can be seen in alerts.json would be:

{"rule":{"level":3,"comment":"Windows Logon
Success.","sidid":18107,"firedtimes":10042,"groups":["windows","authentication_success"],"PCI_DSS":["10.2.5"]},"dstuser":"INF-EX01$","full_log":"2016
Apr 27 11:08:39 WinEvtLog: Security: AUDIT_SUCCESS(4624):
Microsoft-Windows-Security-Auditing: INF-EX01$: OCCAM:
INF-NGD-ADC01.occam-dm.com: An account was successfully logged on. Subject:
 Security ID:  S-1-0-0  Account Name:  -  Account Domain:  -  Logon ID:
 0x0  Logon Type:   3  New Logon:  Security ID:
 S-1-5-21-2069765483-516310128-188549912-18611  Account Name:  INF-EX01$
 Account Domain:  OCCAM  Logon ID:  0x1080bb04  Logon GUID:
 {7E308FE1-D689-81C5-CEF2-24E1E5891FE1}  Process Information:  Process ID:
 0x0  Process Name:  -  Network Information:  Workstation Name:   Source
Network Address: 10.10.10.165  Source Port:  24445  Detailed Authentication
Information:  Logon Process:  Kerberos  Authentication Package: Kerberos
 Transited Services: -  Package Name (NTLM only): -  Key Length:  0  This
event is generated when a logon session is created. It is generated on the
computer that was accessed.
","id":"4624","status":"AUDIT_SUCCESS","data":"Microsoft-Windows-Security-Auditing","systemname":"
INF-NGD-ADC01.occam-dm.com","decoder":{"name":"windows"},"hostname":"INF-NGD-ADC01","agentip":"10.64.10.5","timestamp":"2016
Apr 27 11:08:41","location":"WinEvtLog"}


Am I correct in assuming because the logstash template uses the input of
/var/ossec/log/alerts/alerts.json then I would look for a regular
expression to use as the source for geoip data? The reason we aren't seeing
GeoIP data is that these logs do not contain "srcip" if my understanding is
correct.

Thanks,
Steve

**Comment by snaow** [comment]
You are right about the srcip field, first we need the create a special decoder to extract "srcip" from your Windows Log (Source Network Address), once the alerts have this field, Logstash will do the GeoMapping.

So we have two different approaches here, extract the field using Logstash grok, or create a new decoder in order to extract the IP, I think that creating the decoder is the best choice.

Open Windows decoder file ``/var/ossec/etc/ossec_decoders/windows_decoders.xml
``, go to line 410 and just below _windows-EvtLog_ decoder add this new one:

```
<!-- WinEvtLog Generic + SRC IP -->
<decoder name="windows-EvtLog">
  <type>windows</type>
  <parent>windows</parent>
  <regex offset="after_regex">Source Network Address: (\.+) </regex>
  <order>srcip</order>
</decoder>
```

Save the file and restart OSSEC.
You can verify if it is working by using ossec-logtest tool:


```
2016 Apr 27 11:08:39 WinEvtLog: Security: AUDIT_SUCCESS(4624): Microsoft-Windows-Security-Auditing: INF-EX01$: OCCAM: INF-NGD-ADC01.occam-dm.com: An account was successfully logged on. Subject: Security ID:  S-1-0-0  Account Name:  -  Account Domain:  -  Logon ID:  0x0  Logon Type:   3  New Logon:  Security ID: S-1-5-21-2069765483-516310128-188549912-18611  Account Name:  INF-EX01$  Account Domain:  OCCAM  Logon ID:  0x1080bb04  Logon GUID: 7E308FE1-D689-81C5-CEF2-24E1E5891FE1}  Process Information:  Process ID: 0x0  Process Name:  -  Network Information:  Workstation Name:  Source Network Address: 10.10.10.165  Source Port:  24445  Detailed Authentication Information:  Logon Process:  Kerberos  Authentication Package: Kerberos  Transited Services: -  Package Name (NTLM only): -  Key Length:  0  This event is generated when a logon session is created. It is generated on the computer that was accessed.
...
**Phase 2: Completed decoding.
       decoder: 'windows'
       status: 'AUDIT_SUCCESS'
       id: '4624'
       extra_data: 'Microsoft-Windows-Security-Auditing'
       dstuser: 'INF-EX01$'
       system_name: 'INF-NGD-ADC01.occam-dm.com'
       srcip: '10.10.10.165'
```
Now Windows alerts should have the field "srcip" included and Logstash will do the GeoIP location.

Please don't hesitate to ask if you have any questions, I'll be happy to help. If you like, show us some screenshots of the alerts on Kibana, will be awesome to see how the GeoIP location is going with Windows events.

Best regards,

Pedro S.

**Comment by stephenh1991** [comment]
Hi Pedro,

This is perfect thank you! Worked first time! :)

Here is the screenshot of some of our Romanian users accessing our OWA:

[image: Inline image 1]

Thanks again for all your help!
Steve

**Comment by snaow** [comment]
You are very welcome, I will close the issue, don't hesitate to create another issue or reopen this one if you need it.

Thanks for your feedback and contribution, best regards,

Pedro S.

**Comment by tnacnud1** [comment]
Pedro, thank you very much for including the example! It worked perfectly for me as well.

**Comment by snaow** [comment]
You are very welcome! Don't lose the opportunity to check out our mailing lists in case you want some more info or have some more doubts.

See ya!
