### ISSUE TITLE
Bundled kibana4 init Script Runs As Root

### ISSUE THREAD

**Issue by cdecker22** [wazuh/ossec-wazuh#29]
The kibana4 init script that is included in _extensions/kibana_ runs the service as root.  Kibana listens on a non-privileged port, so it'd be great if the service ran as an unprivileged account.

It appears that the upstream provider of this script added support for defining a user on May 20th:
https://github.com/akabdog/scripts/commit/52bf2ced751be7c4ce04a1dbec48347a56ec019d

Could we get those changes merged in (I am not savvy enough to submit a pull request)?

**Comment by snaow** [comment]
Hi @cdecker22,

You are totally right, it makes sense to me. 

The point is Kibana has recently released it's own repository, so we can install it by using yum or apt-get, the service(init script) is built-in.
The init script in this case can run as an unprivileged account:

> chroot --userspec "$user":"$group" "$chroot" sh -c "

[More info about installing Kibana using repositories.](https://www.elastic.co/guide/en/kibana/current/setup.html#setup-repositories)

Kibana 4.5 is fully compatible with Wazuh so feel free to install it using the repositories, we have updated Wazuh documentation and we will release it soon.

Thanks so much for your feedback, please don't hesitate to ask anything you need.

**Comment by cdecker22** [comment]
@snaow : Thanks for responding so quickly.  I had actually installed kibana via the official RPM and realized it included an init script shortly after creating my issue.
