### ISSUE TITLE
Add support for Xenial

### ISSUE THREAD

**Issue by awainer** [wazuh/ossec-wazuh#31]
Ubuntu 16.04 was released on April and will be a LTS distro, it would be nice to have packages for this release. As it is, this module cannot be used on 16.04.

**Comment by santiago-bassett** [comment]
Hi @awainer, we already built the packages for Ubuntu Xenial for OSSEC. You should be able to find those in our documentation and also in OSSEC website.

We are also in the process of creating packages for our fork. We expect to release a new version with significant changes (both at a manager and at an agent level) in the next couple of months, hopefully with good documentation and installation packages all at the same time.

thanks for reporting the issue and best regards

**Comment by awainer** [comment]
Awesome! 
Thanks and keep up the good work :)
