### ISSUE TITLE
Invalid query in Kibana visualization "High Risk Alerts / PCI DSS"

### ISSUE THREAD

**Issue by tikhon-clearscale** [wazuh/ossec-wazuh#33]
Hello,

Looks like I found small mistake in file kibana-ossecwazuh-dashboards.json, string 574 - query is a "rule.AlertLevel > 10", but I think it should be "rule.AlertLevel: { 10 TO *}".

**Comment by snaow** [comment]
Hi @tikhon-clearscale,

You are totally right, we already fixed it (https://github.com/wazuh/ossec-wazuh/commit/d67a85419ec1f8f3feeb70357f9e6daf34d38b23). We set the inclusive brackets to include alert level 10 in the query, so the final query will be "AlertLevel greater than or equal to 10".

For the next release we are preparing a new set of dashboards and visualizations.

Thanks you so much for your contribution, we really appreciate it.

Best regards,

Pedro S.

**Comment by tikhon-clearscale** [comment]
Thanks a lot!
