### ISSUE TITLE
What does wazuh mean, and how to pronounce?

### ISSUE THREAD

**Issue by GeiliCode** [wazuh/ossec-wazuh#35]
I'm curious, and didn't find the answer through Google.

**Comment by santiago-bassett** [comment]
Hi @GeiliCode, 

we are still trying to figure out what Wazuh means 👍 

We do have a little blue Wolf as a logo, so I personally think that the 'W' is for the Wolf, and 'azuh' is very similar to 'azul' (blue in Spanish). 

Regarding pronunciation I say 'Wazu' (I guess how it would sound in Spanish), but I've heard it in many different ways :-)

Best regards!

**Comment by GeiliCode** [comment]
:-) Thank you very much

**Comment by ASalazarMX** [comment]
I'm sorry to revive this closed issue, but have this been defined? I don't even know if it's "wá-zu" or "wa-zú". Is it wrong to pronounce it like "[Gazoo](https://en.wikipedia.org/wiki/The_Great_Gazoo)"?

**Comment by astateofmind01** [comment]
I like to think about it like the old budweiser add .. waazzzzaaaaaa ;)

**Comment by hex-m** [comment]
The wolf-logo seems to be gone? The latest videos in the [official YouTube channel](https://www.youtube.com/@wazuhsecurity) pronounce it something like "whasa".
