### ISSUE TITLE
syntax error in host-deny.sh

### ISSUE THREAD

**Issue by fgth** [wazuh/ossec-wazuh#37]
Hi, not sure that it's the right section for this issue, sorry if not. I've installed rpm packages from "WAZUH OSSEC Repository" on some centOS7 servers and found a problem with host-deny.sh.
At lines 114 and 117, whitespaces around the "=" sign after TMP_FILE cause a bash error ("command not found"). Removing whitespaces solves the problem.
Regards.

**Comment by vikman90** [comment]
Hi @fgth. 

This is a known issue that has been fixed at OSSEC HIDS v2.9-beta06: https://github.com/ossec/ossec-hids/commit/c97f566e415756b17a3093bb10dbb3b8d405f284. We'll update the packages on the next stable release.

On the other hand, Wazuh HIDS v1.1.1 has also this problem fixed and it's available in the same repository.

Best regards.
