### ISSUE TITLE
Ubuntu 16.04 Repo signature key SHA1 (apt 1.2.7)

### ISSUE THREAD

**Issue by ryandaniels** [wazuh/ossec-wazuh#38]
Ubuntu 16.04 complains about using a weak signature key when running apt-get update.
Is it possible to fix your key to use SHA2?

Followed instructions to install the key:
$ apt-key adv --fetch-keys http://ossec.wazuh.com/repos/apt/conf/ossec-key.gpg.key

$ apt-get update
W: http://ossec.wazuh.com/repos/apt/ubuntu/dists/xenial/InRelease:Signature by key 9FE55537D1713CA519DFB85114B9C8DB9A1B1C65 uses weak digest algorithm (SHA1)

Ref:
# https://github.com/ros-infrastructure/buildfarm_deployment/issues/130

**Comment by jlruizmlg** [comment]
Hi @ryandaniels thanks for your warning, i will review this problem as soon as possible.

**Comment by PhilETaylor** [comment]
![screen shot 2016-08-27 at 10 41 02](https://cloud.githubusercontent.com/assets/400092/18026549/ca29d810-6c42-11e6-8ce2-c0dec20f4f48.png)

and me....

**Comment by jlruizmlg** [comment]
Hi @PhilETaylor and @yandaniels, sorry for the delay, we was working in some modifications over the repository for the new release, now this issue should be fixed.

**Comment by abunasar** [comment]
Same issue, Ubuntu 16.04
