### ISSUE TITLE
Slack Integration Message truncation Issue

### ISSUE THREAD

**Issue by mohakkataria** [wazuh/ossec-wazuh#47]
Hey there,

I had enabled slack integration with OSSEC, but the thing is that the alert messages are getting truncated before they are sent. For e.g. :

2016 Oct 04 13:01:42 test->/var/log/audit/audit.log
Rule:80739 (level 5): Auditd: account state error detected
IP:x.x.x.x
type=USER_ERR msg=audit(1475566301.994:186187): pid=7599 uid=0 auid=4294967295 ses=4294967295 msg= op=PAM:bad_ident acct= ?  exe= /usr/sbin/sshd  hostname=42.104....

The ellipses at the end are generated by the integratord it seems, since i tried logging the contents in the integrations/slack shell script to see as to what content is being generated?

Please help here to fix this.

**Comment by mohakkataria** [comment]
I swifted through the code somewhat, and reached the line number in code which is causing the issue : [https://github.com/wazuh/ossec-wazuh/blob/master/src/os_integrator/integrator.c#L237](https://github.com/wazuh/ossec-wazuh/blob/master/src/os_integrator/integrator.c#L237) . Wanted to know why 165 character limit was put though. :/

**Comment by vikman90** [comment]
Hi @mohakkataria,

as you yourself has written, this limit was imposed intentionally in order not to overload the Slack messages.

Nevertheless I've done some tests and removed the limit of 165 characters. Without it, OSSEC sends up to 1250 bytes per log. I think that it would be interesting to add a new setting to configure the message limit, so everyone can set that value as needed.

We're working on it.
Thank you very much for your feedback.

**Comment by vikman90** [comment]
Hi,

we committed this change in order to solve the problem: https://github.com/wazuh/ossec-wazuh/commit/9f487eaa1fb156147f1d1f87e48b242d7a343e89. It's on the master branch and it will be available officially on out next release.

There is a new per-integration setting called `max_log` that can take a value between 165 and 1024, for example:

>`<integration>`
>&nbsp;&nbsp;&nbsp;&nbsp;`<name>slack</name>`
>&nbsp;&nbsp;&nbsp;&nbsp;`<level>7</level>`
>&nbsp;&nbsp;&nbsp;&nbsp;`<max_log>1024</max_log>`
>&nbsp;&nbsp;&nbsp;&nbsp;`<hook_url>https://hooks.slack.com/services/x/y/z</hook_url>`
>`</integration>`

I hope this is helpful to you.
Best regards.

**Comment by mohakkataria** [comment]
Awesome @vikman90 👍 . Just curious, when is the next release going live?

**Comment by vikman90** [comment]
We're doing some tests and we're planning to launch it later this month.
