### ISSUE TITLE
wazuh-agent rpm is unavailable for EL5 x86_64

### ISSUE THREAD

**Issue by angystardust** [wazuh/ossec-wazuh#48]
While trying to install the Wazuh agent on a 64-bit EL5 host, I noticed that there isn't any rpm package available on your repo (just like the 32-bit arch or the EL6 and EL7 version).
The file location should be http://ossec.wazuh.com/el/5/x86_64/wazuh-agent-1.1.1-2.el5.x86_64.rpm
Maybe it was caused by a failure during the last build (2016-10-21)?
Can you please fix that?
Thanks a lot

P.s.: Looking at the google's cache, it seems that the package existed 'till the 8 Oct 16
http://webcache.googleusercontent.com/search?q=cache:30I-gmtGKdsJ:ossec.wazuh.com/el/5/x86_64/+&cd=1&hl=it&ct=clnk&gl=it&client=ubuntu

**Comment by jlruizmlg** [comment]
Hi @angystardust you are right, let me take a look.

**Comment by jlruizmlg** [comment]
Hi @angystardust, you have the package in the repository again, sorry about this.

In a couple week we will release the new packages version, specific for RHEL, probably the actual package and the new one won't be compatible, but don't worry, we will provide you in our documentation the best way to update the packages.

**Comment by angystardust** [comment]
Hi @jlruizmlg thank you very much for your super-fast reply and solution.
I was just wondering in which way the older and the newer package won't be compatible (files conflicts?)...so we can't just do a _yum update wazuh-agent_ through **ansible**?

**Comment by jlruizmlg** [comment]
Hi @angystardust the package for RedHat will have different content than the package for CentOS.
The new installation will be easy as well, only uninstall the version 1.1.1 change repository to a new one and install your RedHat version.

**Comment by angystardust** [comment]
Ok but it isn't so clear to me why you're going to build different packages for CentOS and RH as they both are ABI-compatible

**Comment by jlruizmlg** [comment]
With the new release we will include Scap policies, and this policies are different for each OS, if we include all content (for RHEL and CentOS) in the same RPM, the rpm size is over 70mb, but if we split in two RPMS one per OS, we can reduce the package almost half from the original size.

You can found more information here:
[https://github.com/wazuh/wazuh-documentation/blob/in-progress/source/wazuh_modules_openscap.rst#scap-policies](https://github.com/wazuh/wazuh-documentation/blob/in-progress/source/wazuh_modules_openscap.rst#scap-policies)

As you see this documentation are in progress so our apologies if are not 100% correct yet.

The Oscap policies:
[https://github.com/wazuh/ossec-wazuh/tree/master/wodles/oscap/content](https://github.com/wazuh/ossec-wazuh/tree/master/wodles/oscap/content)

**Comment by jlruizmlg** [comment]
@angystardust can you confirm if the repository is working now in order to close the issue? Thanks.

**Comment by angystardust** [comment]
Yes, now the repo is working as expected.
Thank you so much for your support :100:

**Comment by jlruizmlg** [comment]
cool thanks for your feedback!!
