### ISSUE TITLE
upgraded to wazuh's OSSEC, and ossec-remoted no longer finds the client keys

### ISSUE THREAD

**Issue by seefood** [wazuh/ossec-wazuh#50]
I had ossec installed from source on a machine (Amazon Linux, somewhat RHEL6-like), and I have now stopped it, installed with your puppet module (from the el6 rpm) and copied over the old client.keys file to /var/ossec/etc/.
however on each restart, ossec-remoted says it can't find the file and dies:
```
2016/11/02 13:17:04 ossec-remoted(4111): INFO: Maximum number of agents allowed: '16384'.
2016/11/02 13:17:04 ossec-remoted(1410): INFO: Reading authentication keys file.
2016/11/02 13:17:04 ossec-remoted(1103): ERROR: Unable to open file '/etc/client.keys'.
2016/11/02 13:17:04 ossec-remoted(1750): ERROR: No remote connection configured. Exiting.
```
I have no idea where it got the path from, but I copied the file there just in case, and it still quits. the file is definitely full of the old clients' details and manage_agents sees it fine. What am I missing?

**Comment by jlruizmlg** [comment]
Hi @seefood 

What are the permissions in the file? should be root:ossec

**Comment by seefood** [comment]
oh duh. didn't occur to me it would be that silly. well, that error message needs to reflect the real problem then :)

**Comment by jlruizmlg** [comment]
haha you are right maybe the message can be a little more clear, thanks for your feedback as always!! @seefood
