### ISSUE TITLE
Importing Ossec alerts index gives error

### ISSUE THREAD

**Issue by greyhammer** [wazuh/ossec-wazuh#54]
I get the following error when importing the ossec alerts index. 

`Error: Could not locate that index-pattern-field (id: SyscheckFile.path)
    at FieldAggParamFactory.FieldAggParam.deserialize (https://54.92.229.48/bundles/kibana.bundle.js?v=10000:85866:16)
    at https://54.92.229.48/bundles/kibana.bundle.js?v=10000:91516:29
    at Array.forEach (native)
    at AggConfigFactory.AggConfig.fillDefaults (https://54.92.229.48/bundles/kibana.bundle.js?v=10000:91494:28)
    at new AggConfig (https://54.92.229.48/bundles/kibana.bundle.js?v=10000:91408:13)
    at https://54.92.229.48/bundles/kibana.bundle.js?v=10000:92112:19
    at Array.map (native)
    at new AggConfigs (https://54.92.229.48/bundles/kibana.bundle.js?v=10000:92110:35)
    at VisFactory.Vis.setState (https://54.92.229.48/bundles/kibana.bundle.js?v=10000:85312:20)
    at SavedVis._updateVis (https://54.92.229.48/bundles/kibana.bundle.js?v=10000:93999:17)`

I also get the following error when viewing the ossec Alerts Dashboard

`Error: Request to Elasticsearch failed: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Expected geo_point type on field [GeoLocation.location], but got [double]"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"ossec-2016.11.21","node":"Y_yAabWIRHuj7pdKx_aDqg","reason":{"type":"illegal_argument_exception","reason":"Expected geo_point type on field [GeoLocation.location], but got [double]"}}]}}
    at https://54.92.229.48/bundles/kibana.bundle.js?v=10000:81088:39
    at Function.Promise.try (https://54.92.229.48/bundles/commons.bundle.js?v=10000:61158:23)
    at https://54.92.229.48/bundles/commons.bundle.js?v=10000:61127:31
    at Array.map (native)
    at Function.Promise.map (https://54.92.229.48/bundles/commons.bundle.js?v=10000:61126:31)
    at callResponseHandlers (https://54.92.229.48/bundles/kibana.bundle.js?v=10000:81060:23)
    at https://54.92.229.48/bundles/kibana.bundle.js?v=10000:80561:17
    at processQueue (https://54.92.229.48/bundles/commons.bundle.js?v=10000:42404:29)
    at https://54.92.229.48/bundles/commons.bundle.js?v=10000:42420:28
    at Scope.$eval (https://54.92.229.48/bundles/commons.bundle.js?v=10000:43648:29)`

Not sure if they are related or not. Might be user error. 
Im running this on Ubuntu 14.04.  Fresh install. 

I used the guide here http://documentation.wazuh.com/en/latest/installation.html

**Comment by snaow** [comment]
Hi @greyhammer, 

Thanks for give it a try to Wazuh.

What Elastic Version are you running? What elastic template are you importing? What dashboard file are you importing?

It seems like you did not load the mapping/template properly or you got an alert before the mapping was applied.
I can see how you have fields type inconsistencies:

> "Expected geo_point type on field [GeoLocation.location], but got [double]"

Elasticsearch by default generates an automatic mapping when creating a document, that mapping does not have the fields types we need, that's why we need to have the proper mapping/template installed before sending anything to Elastic.

To solve the issue we will need to reindex all the indices, the process is create a new copy, delete the originals and rename the copy back. If you don't mind to loose your current data, the easiest solution will be to delete all the indices and start over.
You can do that by running the following commands:

Stop Logstash
```service stop logstash```

Stop Kibana
```service stop kibana```

Remove indices
```curl -XDELETE http://localhost:9200/ossec-*```

Remove template
```curl -XDELETE http://localhost:9200/_template/ossec```

Verify there is no ossec template:
```curl -XGET http://192.168.1.10:9200/_template```

Verify there is no mappings for ossec-*
```curl -XGET http://192.168.1.10:9200/_mappings/```

Load again the template (choose between elastic5 or elastic)
```curl -XPUT -v -H "Expect:"  "http://localhost:9200/_template/ossec" -d@/etc/logstash/elastic5-ossec-template.json```

The output should be: "{"acknowledged":true}"

Start Logstash, Start Kibana
```service start logstash```
```service start kibana```


You can verify what mapping is working on your index, it must be identical to the mapping you are loading with curl -XPUT.

```http://192.168.1.10:9200/ossec-2016.11.22/_mapping```

I hope it helps, Please let me know if you need anything.

Regards,

Pedro.

**Comment by greyhammer** [comment]
Elastic Search Version 

`root@ip-10-0-0-71:~# curl -XGET 'localhost:9200'
{
  "name" : "ossec_node1",
  "cluster_name" : "ossec",
  "cluster_uuid" : "151FUZrRRuu4ziim87-brg",
  "version" : {
    "number" : "2.4.1",
    "build_hash" : "c67dc32e24162035d18d6fe1e952c4cbcbe79d16",
    "build_timestamp" : "2016-09-27T18:57:55Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.2"
  },
  "tagline" : "You Know, for Search"
}`

**Comment by greyhammer** [comment]
And this is the output of this step 

```
curl -XPUT -v -H "Expect:" "http://localhost:9200/_template/ossec" -d@/etc/logstash/elastic5-ossec-template.json

 Hostname was NOT found in DNS cache
 Trying 127.0.0.1...
 Connected to localhost (127.0.0.1) port 9200 (#0)
 PUT /_template/ossec HTTP/1.1
 User-Agent: curl/7.35.0
 Host: localhost:9200
 Accept: */*
 Content-Length: 10368
 Content-Type: application/x-www-form-urlencoded

 upload completely sent off: 10368 out of 10368 bytes
 HTTP/1.1 400 Bad Request
 Content-Type: application/json; charset=UTF-8
 Content-Length: 391

Connection #0 to host localhost left intact
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [keyword] declared on field [srcip]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [ossec]: No handler for type [keyword] declared on field [srcip]","caused_by":{"type":"mapper_parsing_exception","reason":"No handler for type [keyword] declared on field [srcip]"}},"status":400}
```

**Comment by greyhammer** [comment]
And then this command 

```
curl -XGET 'http://localhost:9200/ossec-2016.11.22/_mapping'
{"ossec-2016.11.22":{"mappings":{"ossec":{"dynamic_templates":[{"notanalyzed":{"mapping":{"index":"not_analyzed","type":"string","doc_values":"true"},"match":"*","match_mapping_type":"string"}}],"properties":{"@timestamp":{"type":"date","format":"dateOptionalTime"},"@version":{"type":"string"},"AgentIP":{"type":"string","index":"not_analyzed"},"AgentName":{"type":"string","index":"not_analyzed"},"AlertsFile":{"type":"string","index":"not_analyzed"},"GeoLocation":{"properties":{"area_code":{"type":"long"},"city_name":{"type":"string","index":"not_analyzed"},"continent_code":{"type":"string"},"coordinates":{"type":"double"},"country_code2":{"type":"string"},"country_code3":{"type":"string"},"country_name":{"type":"string","index":"not_analyzed"},"dma_code":{"type":"long"},"ip":{"type":"string","index":"not_analyzed"},"latitude":{"type":"double"},"location":{"type":"geo_point"},"longitude":{"type":"double"},"postal_code":{"type":"string"},"real_region_name":{"type":"string","index":"not_analyzed"},"region_name":{"type":"string","index":"not_analyzed"},"timezone":{"type":"string"}}},"SyscheckFile":{"properties":{"gowner_after":{"type":"string","index":"not_analyzed"},"gowner_before":{"type":"string","index":"not_analyzed"},"md5_after":{"type":"string","index":"not_analyzed"},"md5_before":{"type":"string","index":"not_analyzed"},"owner_after":{"type":"string","index":"not_analyzed"},"owner_before":{"type":"string","index":"not_analyzed"},"path":{"type":"string","index":"not_analyzed"},"perm_after":{"type":"string","index":"not_analyzed"},"perm_before":{"type":"string","index":"not_analyzed"},"sha1_after":{"type":"string","index":"not_analyzed"},"sha1_before":{"type":"string","index":"not_analyzed"}}},"action":{"type":"string","index":"not_analyzed"},"command":{"type":"string","index":"not_analyzed"},"data":{"type":"string","index":"not_analyzed"},"decoder":{"properties":{"accumulate":{"type":"long"},"fts":{"type":"long"},"ftscomment":{"type":"string","index":"not_analyzed"},"name":{"type":"string","index":"not_analyzed"},"parent":{"type":"string","index":"not_analyzed"}}},"dstip":{"type":"string","index":"not_analyzed"},"dstport":{"type":"string","index":"not_analyzed"},"dstuser":{"type":"string","index":"not_analyzed"},"full_log":{"type":"string"},"host":{"type":"string","index":"not_analyzed"},"id":{"type":"string","index":"not_analyzed"},"location":{"type":"string","index":"not_analyzed"},"message":{"type":"string"},"offset":{"type":"string"},"path":{"type":"string","index":"not_analyzed"},"program_name":{"type":"string","index":"not_analyzed"},"protocol":{"type":"string","index":"not_analyzed"},"rule":{"properties":{"AlertLevel":{"type":"long"},"CIS":{"type":"string","index":"not_analyzed"},"PCI_DSS":{"type":"string","index":"not_analyzed"},"cve":{"type":"string","index":"not_analyzed"},"description":{"type":"string","index":"not_analyzed"},"firedtimes":{"type":"long"},"frequency":{"type":"long"},"groups":{"type":"string","index":"not_analyzed"},"info":{"type":"string","index":"not_analyzed"},"sidid":{"type":"long"}}},"srcip":{"type":"string","index":"not_analyzed"},"srcuser":{"type":"string","index":"not_analyzed"},"status":{"type":"string","index":"not_analyzed"},"systemname":{"type":"string","index":"not_analyzed"},"type":{"type":"string"},"url":{"type":"string","index":"not_analyzed"}}}}}}
```

**Comment by snaow** [comment]
Hi again @greyhammer,

I can tell you what is happening on your installation.

Your cluster version (Elasticsearch version) is 2.4.1 but you are loading template version for Elasticsearch 5.0.1.
Please, stop using "elastic5-ossec-template.json" and use instead "elastic-ossec-template.json".
I know last time I sent you the commands using "Elastic5" version, I assumed you were on Elastic 5, sorry about that.

You can redo the steps using the right JSON template. 
Please remember (because you are on Elastic 2.4), importing file "kibana-ossecwazuh-dashboards.json" at Kibana for dashboards and visualizations, remove current visualization dashboards and re-import the correct ones.

We are preparing new documentation in order to make the installation process easier.

Hope it helps, don't doubt to write here if you need anything more.

**Comment by greyhammer** [comment]
I believe that fixed it for me.  Thanks

**Comment by snaow** [comment]
Great! I will close the issue, don't doubt to reopen it if you need.

Regards,
Pedro.

**Comment by GoaPhuDen** [comment]
And this is the output:

curl -XPUT -v -H "Expect:" "http://localhost:9200/_template/ossec" -d@/root/wazuh-1.1.1/extensions/elasticsearch/elastic-ossec-template.json
* About to connect() to localhost port 9200 (#0)
*   Trying 127.0.0.1... connected
* Connected to localhost (127.0.0.1) port 9200 (#0)
> PUT /_template/ossec HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.21 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: localhost:9200
> Accept: */*
> Content-Length: 8746
> Content-Type: application/x-www-form-urlencoded
> 
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=UTF-8
< Content-Length: 21
< 
* Connection #0 to host localhost left intact
* Closing connection #0
{"acknowledged":true}[root@logstash conf.d]#
