### ISSUE TITLE
ossec-reportd

### ISSUE THREAD

**Issue by johnfugazi** [wazuh/ossec-wazuh#6]
trying to run ossec-reportd and I am not receiving any info.  I am using the following command from ossec website.

cat /var/ossec/logs/alerts/alerts.json | /var/ossec/bin/ossec-reportd -f level 10

I changed the "alerts.log" to "alerts.json".  when I run this I get the reported has complete and there are zero alerts.
if I run the report with the "alerts.log", I get "invalid pointer"

**Comment by santiago-bassett** [comment]
I can confirm it is failing: 

root@vpc-ossec-manager:~# cat /var/ossec/logs/alerts/alerts.log | /var/ossec/bin/ossec-reportd -f group authentication
2015/12/23 20:34:13 ossec-reportd: INFO: Started (pid: 20244).
*** Error in `/var/ossec/bin/ossec-reportd': double free or corruption (out): 0x00000000023efd10 ***
Aborted (core dumped)

**Comment by snaow** [comment]
I ran some test, seems like this functionality is broken on OSSEC 2.9 (master branch of ossec-hids) and in our fork.
Currently you need to install OSSEC version 2.8.3 to use ossec-reportd.

We are working on fix this tool and it will be ready soon.

Thanks for the feedback, happy christmas.

**Comment by johnfugazi** [comment]
I took a copy of the "ossec-reportd" and replace it on the ossec-wazuh fork.  it is working as it should.

thanks

**Comment by snaow** [comment]
Glad to hear. We will fix the compilation process so manual copy won't be necessary. 

Thanks again for the feedback.

**Comment by snaow** [comment]
ossec-reportd binary has been fixed on PR: https://github.com/wazuh/ossec-wazuh/pull/8

Now, you can run:

``cat /var/ossec/logs/alerts/alerts.log | /var/ossec/bin/ossec-reportd -f group authentication``

Thanks.
